---
title: London Mathematical Society joins the Levelling Up scheme
date: '2020-08-06'
slug: lms
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-24T20:26:04-05:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Read the [press release](https://www.lms.ac.uk/news-entry/06082020-1524/levelling-scheme) from the London Mathematical Society below:

<!--more-->

> Thanks to a generous donation from Dr Tony Hill, the LMS has started work on a new venture to support the provision of online tutoring for A-level Mathematics students who come from backgrounds that are under-represented in the mathematics community. 

> Working with three or four universities initially, the pilot aims to bring together undergraduate student tutors with A-level mathematics students who wish to improve their grades to enable them to read a STEM degree. Each university would identify nearby schools with significant percentages of students from under-represented backgrounds and enlist the help of undergraduate students to tutor and engage with their A-level tutees.

> Through enhancing the A-level students’ engagement with mathematics, the Levelling Up Scheme aims to increase the diversity of students pursuing STEM degrees and, eventually, careers. Through providing mentoring to the tutors from experienced teachers, the scheme also aims to enrich the tutors’ teaching skills and knowledge, and improve the foundation on which they build the next step in their careers.


